# --------------------------------------------------------
# References:
# BrainJEPA: https://github.com/Eric-LRL/Brain-JEPA
# --------------------------------------------------------

import math
from functools import partial
import numpy as np
from torch.autograd import Function                   
from collections import OrderedDict

import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange

try:
    from flash_attn import flash_attn_func
    from flash_attn import flash_attn_varlen_func
    HAS_FLASH_ATTENTION = True
except ImportError:
    HAS_FLASH_ATTENTION = False
from .patch_embed import PatchEmbed


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def apply_masks(x, masks):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param masks: list of tensors containing indices of patches in [N] to keep
    """
    all_x = []
    for m in masks:
        mask_keep = m.unsqueeze(-1).repeat(1, 1, x.size(-1))
        all_x += [torch.gather(x, dim=1, index=mask_keep)]
    return torch.cat(all_x, dim=0)

def drop_path(x, drop_prob: float = 0., training: bool = False):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x

class LayerScale(nn.Module):
    def __init__(
            self,
            dim: int,
            init_values: float = 1e-5,
            inplace: bool = False,
    ) -> None:
        super().__init__()
        self.inplace = inplace
        self.gamma = nn.Parameter(init_values * torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x.mul_(self.gamma) if self.inplace else x * self.gamma
    
class Attention(nn.Module):
    def __init__(self, dim, 
                 num_heads=8, 
                 qkv_bias=False, 
                 qk_scale=None,
                 qk_norm=False,
                 proj_bias=True,
                 attn_drop=0.,
                 proj_drop=0., 
                 attn_mode='normal',
                 is_causal=False,
                 gate_attention='none'):
        super().__init__()
        self.num_heads = num_heads
        self.dim = dim
        self.head_dim = dim // num_heads
        self.scale = qk_scale or self.head_dim ** -0.5
        self.gate_attention = gate_attention

        self.q_aug_dim = 0
        if gate_attention == 'headwise':
            self.q_aug_dim = self.num_heads
        elif gate_attention == 'elementwise':
            self.q_aug_dim = dim
        total_dim = dim * 3 + self.q_aug_dim

        self.qkv = nn.Linear(dim, total_dim, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim, bias=proj_bias)
        self.proj_drop = nn.Dropout(proj_drop)
        self.proj_drop_rate = proj_drop
        self.is_causal = is_causal
        self.attn_mode = attn_mode

        self.q_norm = nn.LayerNorm(self.head_dim, eps=1e-12) if qk_norm else nn.Identity()
        self.k_norm = nn.LayerNorm(self.head_dim, eps=1e-12) if qk_norm else nn.Identity()

    def forward(self, x, return_attn=None, cu_seqlens=None, max_seqlen=None):
        if torch.isnan(x).any():
             print("!!! [Attention Input] x contains NaN!")

        is_packed = x.ndim == 2  # (Total, C) packed input
        if is_packed:
            Total, C = x.shape
            B, N = 1, Total
        else:
            B, N, C = x.shape
        attn = None
        qkv = self.qkv(x)

        # Keep Q, K, V aligned; place gate projection at the end to avoid misaligned offsets for flash-attn
        q, k, v, gate = torch.split(qkv, [self.dim, self.dim, self.dim, self.q_aug_dim], dim=-1)
        if self.gate_attention == 'headwise' and self.q_aug_dim > 0:
            # Gate: (..., num_heads) -> (..., num_heads, 1)
            gate = gate.view(*gate.shape[:-1], self.num_heads, 1)
        elif self.gate_attention == 'elementwise' and self.q_aug_dim > 0:
            # Gate: (..., dim) -> (..., num_heads, head_dim)
            gate = gate.view(*gate.shape[:-1], self.num_heads, self.head_dim)
        else:
            gate = None

        # Ensure contiguous buffers before feeding flash-attn kernels
        q = q.contiguous()
        k = k.contiguous()
        v = v.contiguous()
        if gate is not None:
            gate = gate.contiguous()

        if self.attn_mode == 'normal':
            q = q.reshape(B, N, self.num_heads, self.head_dim).permute(0, 2, 1, 3)
            k = k.reshape(B, N, self.num_heads, self.head_dim).permute(0, 2, 1, 3)
            v = v.reshape(B, N, self.num_heads, self.head_dim).permute(0, 2, 1, 3)

            q, k = self.q_norm(q), self.k_norm(k)

            if self.is_causal:
                q_len, k_len = q.size(-2), k.size(-2)
                causal_mask = torch.triu(
                    torch.full((q_len, k_len), float("-inf"), device=q.device),
                    diagonal=1,
                ).to(q.dtype)
            out = F.scaled_dot_product_attention(q, k, v,
                attn_mask=causal_mask if self.is_causal else None,
                dropout_p=self.attn_drop.p if self.training else 0.0
            )
            out = out.transpose(1, 2)  # B, N, H, D

            if gate is not None:
                # Gate: (B, N, H, 1) or (B, N, H, D) -> Permute -> (B, H, N, D/1)
                gate = gate.permute(0, 2, 1, 3)
                out = out * F.sigmoid(gate)

            out = out.reshape(B, N, C)

        elif self.attn_mode == 'flash_attn' and HAS_FLASH_ATTENTION:
            if torch.isnan(q).any() or torch.isinf(q).any():
                print("!!! Q contains NaN/Inf BEFORE FlashAttn")

            cu_seqlens = cu_seqlens.to(dtype=torch.int32).contiguous() if cu_seqlens is not None else None

            # Reshape Q, K, V to (Total, Num_Heads, Head_Dim) for flash_attn_varlen_func
            q = q.reshape(-1, self.num_heads, self.head_dim)
            k = k.reshape(-1, self.num_heads, self.head_dim)
            v = v.reshape(-1, self.num_heads, self.head_dim)

            if torch.isnan(q).any(): print("!!! Q is NaN BEFORE Norm")

            q, k = self.q_norm(q), self.k_norm(k)

            if torch.isnan(q).any():
                print(f"!!! Q contains NaN AFTER Norm. Q_Norm Weight: {self.q_norm.weight.mean()}")

            # Cast to bf16/fp16 for flash attention
            if q.dtype == torch.float32:
                target_dtype = torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16
                q = q.to(target_dtype)
                k = k.to(target_dtype)
                v = v.to(target_dtype)
                if gate is not None:
                    gate = gate.to(target_dtype)
            elif gate is not None and gate.dtype != q.dtype:
                gate = gate.to(q.dtype)

            if cu_seqlens is not None and max_seqlen is not None:
                # Variable-length path: cu_seqlens and max_seqlen are pre-computed by the caller.
                # q/k/v are already packed as (Total, H, D) when input x is packed.
                out = flash_attn_varlen_func(
                    q, k, v,
                    cu_seqlens_q=cu_seqlens,
                    cu_seqlens_k=cu_seqlens,
                    max_seqlen_q=max_seqlen,
                    max_seqlen_k=max_seqlen,
                    dropout_p=self.proj_drop_rate if self.training else 0.0,
                    softmax_scale=self.scale,
                    causal=self.is_causal,
                )
                out = out.reshape(B, N, self.num_heads, self.head_dim)  # Reshape back to (B, N, H, D)
            else:
                # Fixed-length path: reshape to (B, N, H, D) for flash_attn_func
                q = q.reshape(B, N, self.num_heads, self.head_dim)
                k = k.reshape(B, N, self.num_heads, self.head_dim)
                v = v.reshape(B, N, self.num_heads, self.head_dim)
                out = flash_attn_func(q, k, v, dropout_p=self.proj_drop_rate if self.training else 0.0, causal=self.is_causal)
            if return_attn:
                out, attn, _ = flash_attn_func(q, k, v, dropout_p=self.proj_drop_rate if self.training else 0.0, causal=self.is_causal, return_attn_probs=True)

            if out.dtype != x.dtype:
                out = out.to(x.dtype)

            if gate is not None:
                out = out * F.sigmoid(gate)

            # Reshape back to input shape
            if is_packed:
                out = out.reshape(N, C)
            else:
                out = out.reshape(B, N, C)
        else:
            raise Exception('error')
            
        x = self.proj(out)
        x = self.proj_drop(x)
        if return_attn:
            return x, attn
        return x, None

class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, qk_norm=False,
                 proj_bias=True, drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm, attn_mode='normal', attn_causal=False, gate_attention='none', init_values=None):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, qk_norm=qk_norm,
            proj_bias=proj_bias, attn_drop=attn_drop, proj_drop=drop, attn_mode=attn_mode,
            is_causal=attn_causal, gate_attention=gate_attention,
        )
        self.drop_path1 = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.drop_path2 = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = MLP(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

        self.ls1 = LayerScale(dim, init_values=init_values) if init_values else nn.Identity()
        self.ls2 = LayerScale(dim, init_values=init_values) if init_values else nn.Identity()

    def forward(self, x, return_attention=False, cu_seqlens=None, max_seqlen=None):
        y, attn = self.attn(self.norm1(x), return_attn=return_attention, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen)
        x = x + self.drop_path1(self.ls1(y))
        x = x + self.drop_path2(self.ls2(self.mlp(self.norm2(x))))
        if return_attention:
            return x, attn
        return x

class VisionTransformer(nn.Module):
    """ Vision Transformer """
    def __init__(
        self,
        img_size=(224,224),
        patch_size=16,
        in_chans=1,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4.0,
        qkv_bias=True,
        qk_scale=None,
        qk_norm=False,
        proj_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        norm_layer=nn.LayerNorm,
        init_std=0.02,
        attn_mode='normal',
        gradient_checkpointing=False,
        encoder_mode=False,
        add_cls_token=False,
        attn_causal=False,
        gate_attention='none',
        **kwargs
    ):
        super().__init__()
        self.num_features = self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.gradient_checkpointing = gradient_checkpointing
        # --

        if in_chans == 1 or encoder_mode:
            self.patch_embed = PatchEmbed(
                img_size=img_size,
                patch_size=patch_size,
                in_chans=in_chans,
                embed_dim=embed_dim)
            self.num_patches = self.patch_embed.num_patches
            encoder_mode = True
        else: # decoder
            self.patch_embed = nn.Linear(in_chans, embed_dim)
            self.num_patches = img_size[0] * (img_size[1] // patch_size)
            encoder_mode = False
        
        # -- pos embedding;
        self.pos_embed = nn.Parameter(torch.randn(1, img_size[0], embed_dim))
        if add_cls_token and not encoder_mode:  # seperate cls pos emb for decoder mode
            self.pos_embed_cls_dec = nn.Parameter(torch.zeros(1, 1, embed_dim))
        # --

        if add_cls_token and encoder_mode:
            self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
            self.pos_embed_cls = nn.Parameter(torch.zeros(1, 1, embed_dim))
            torch.nn.init.trunc_normal_(self.cls_token, std=0.02)
        
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                qk_norm=qk_norm, proj_bias=proj_bias, drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i],
                norm_layer=norm_layer, attn_mode=attn_mode, attn_causal=attn_causal, gate_attention=gate_attention)
            for i in range(depth)])
        self.norm = norm_layer(embed_dim)
        # ------
        self.init_std = init_std
        self.apply(self._init_weights)
        self.fix_init_weight()

    def fix_init_weight(self):
        def rescale(param, layer_id):
            param.div_(math.sqrt(2.0 * layer_id))

        for layer_id, layer in enumerate(self.blocks):
            rescale(layer.attn.proj.weight.data, layer_id + 1)
            rescale(layer.mlp.fc2.weight.data, layer_id + 1)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=self.init_std)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            trunc_normal_(m.weight, std=self.init_std)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)

    def forward(self, x, masks=None, return_attention=False, cu_seqlens=None, max_seqlen=None, **kwargs):
        if masks is not None:
            if not isinstance(masks, list):
                masks = [masks]
        # x: (B C V T) or (B N C)

        # -- patchify x
        if x.dtype != self.pos_embed.dtype:
            x = x.to(self.pos_embed.dtype)
        x = self.patch_embed(x)
        B, N, D = x.shape

        # -- add positional embedding to x
        # pos_embed = self.interpolate_pos_encoding(x, pos_embed)
        num_time_patches = N // self.pos_embed.shape[1]
        pos_embed = self.pos_embed.unsqueeze(2).repeat(1, 1, num_time_patches, 1)  # [1, N, T, D]
        pos_embed = pos_embed.reshape(1, -1, D)
        if hasattr(self, 'pos_embed_cls_dec'):
            pos_embed = torch.cat([self.pos_embed_cls_dec, pos_embed], dim=1)
        x = x + pos_embed

        if hasattr(self, 'cls_token'):
            cls_token = self.cls_token + self.pos_embed_cls
            x = torch.cat([cls_token.expand(B, -1, -1), x], dim=1)

        # -- mask x
        if masks is not None:
            x = apply_masks(x, masks)

        # -- fwd prop
        attn_set = []
        for i, blk in enumerate(self.blocks):
            if self.gradient_checkpointing and self.training:
                if return_attention:
                    x, attn = torch.utils.checkpoint.checkpoint(
                        blk, x, return_attention, cu_seqlens, max_seqlen, use_reentrant=False)
                    attn_set.append(attn.detach().cpu())
                else:
                    x = torch.utils.checkpoint.checkpoint(
                        blk, x, False, cu_seqlens, max_seqlen, use_reentrant=False)
            else:
                if return_attention:
                    x, attn = blk(x, return_attention=return_attention, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen)
                    attn_set.append(attn.detach().cpu())
                else:
                    x = blk(x, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen)

        if self.norm is not None:
            x = self.norm(x)
        
        if return_attention:
            return x, attn_set
        return x

    def interpolate_pos_encoding(self, x, pos_embed):
        npatch = x.shape[1] - 1
        N = pos_embed.shape[1] - 1
        if npatch == N:
            return pos_embed
        class_emb = pos_embed[:, 0]
        pos_embed = pos_embed[:, 1:]
        dim = x.shape[-1]
        pos_embed = nn.functional.interpolate(
            pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(0, 3, 1, 2),
            scale_factor=math.sqrt(npatch / N),
            mode='bicubic',
        )
        pos_embed = pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        return torch.cat((class_emb.unsqueeze(0), pos_embed), dim=1)
    
    
def vit_small(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=384, depth=12, num_heads=6, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


def vit_base(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=768, depth=12, num_heads=12, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


def vit_large(patch_size=16, **kwargs):
    model = VisionTransformer(
        patch_size=patch_size, embed_dim=1024, depth=24, num_heads=16, mlp_ratio=4,
        qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    return model


VIT_EMBED_DIMS = {
    'vit_small': 384,
    'vit_base': 768,
    'vit_large': 1024,
}


if __name__ == '__main__':
    # Example usage
    model = vit_base(patch_size=32, img_size=(450, 490), in_chans=1).cuda()
    x = torch.randn(2, 1, 450, 490).cuda()
    output = model(x)
    print(output.shape)